            .text

start:      mv a0, zero
            mv t1, zero
            mv t2, zero
            mv t0, zero
            mv t0, zero
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            addi a0, a0, 1
            addi t1, t1, 2
            addi t2, t2, 3 # iter
            